name: Update Swagger Doc from Main

on:
  push:
    branches:
      - main
    paths:
      - 'snippets/sdk/**'
      - 'api-reference/swagger-spec.json'

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  update-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'

      - name: Install dependencies
        run: |
          cd fern
          npm install

      - name: Update swagger doc
        run: node fern/scripts/merge_snippets_to_spec.js

      - name: Create PR with changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! git diff --quiet api-reference/swagger-doc.json; then
            sync_branch="update-swagger-$(date +"%Y-%m-%d-%H%M%S")"
            git checkout -b "$sync_branch"
            git add api-reference/swagger-doc.json
            
            title="[Automated] Update swagger-doc.json from commit \`$(echo "${{ github.sha }}"|cut -c-7)\`"
            xref="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            
            git commit -m "$title"
            git push -u origin "$sync_branch"

            gh pr create \
                --base main \
                --head "$sync_branch" \
                --title "$title" \
                --body "This PR updates the swagger-doc.json file based on changes in SDK snippets or swagger spec.

Ref: $xref" \
                --assignee ${{ github.actor }}
          fi 